### ISSUE TITLE
Phrase List 3

### ISSUE THREAD

**Issue by Greenactivist** [yawnoc/stroke-input-data#10]
Some more phrases you might want to consider.  I hope you can find something useful here!

The information goes two ways as I have found some of your phrases make useful entries to my dictionary.  I particularly like the Cantonese phrases - I really ought to learn Cantonese.

===============================================|

List of phrases using simplified Chinese Characters
Compiled by Bernard Hurley
Released unequivocally to the public domain

大一
大丈夫主义
大三
大不相同
大业
大中华区
大中学生
大为
大主教
大举
大义
大义凛然
大乌鸦
大二
大亨
大人物
大仙
大件
大众传播
大众化
大众汽车
大伙
大伙儿
大会
大伤元气
大体
大体上
大作宣传
大佬
大侠
大便
大修
大修道院
大傻瓜
大儿子
大全
大公司
大公无私
大兴
大兴土木
大写字母
大军
大农场
大减价
大凡
大凡粗知
大刀
大刀阔斧
大前年
大前提
大剪刀
大副
大力
大力发展
大力士
大功
大动脉
大勇若怯
大包大揽
大千世界
大半
大卡
大卫
大厦将倾
大厨
大发雷霆
大变
大口
大口径
大叫一声
大可不必
大号
大吃
大吃一惊
大吃二喝
大吃大喝
大吃特吃
大吃苦头
大合唱
大吉
大同小异
大名
大名鼎鼎
大后年
大吵
大吵大闹
大吹大擂
大呼小叫
大哥大
大哭
大唐
大喊
大喊大叫
大喜
大喜过望
大喝一声
大四
大国
大坏蛋
大坑
大块头
大块朵颐
大坝
大型企业
大堂
大声叫喊
大声疾呼
大声说话
大处着眼
大多数人
大大
大大咧咧
大大小小
大大方方
大失所望
大头目
大女儿
大妈
大姐
大姑
大姨
大娘
大媒
大字不识一个
大学城
大学本科
大学预科
大宗
大官
大客车
大家闺秀
大富大贵
大寺院
大将
大将军
大尉
大小写
大小姐
大局
大峡谷
大巴
大幅度
大年三十
大度
大开
大弟弟
大张声势
大彻大悟
大志
大忙人
大快人心
大快朵颐
大怒
大总统
大惊
大惊失色
大惑不解
大愚
大户
大手大脚
大才小用
大投资家
大拇指
大括号
大指
大捕头
大排档
大提琴手
大摆宴席
大放厥辞
大放异彩
大放悲声
大敌当前
大教堂
大数
大族
大旗
大无畏
大显神通
大显身手
大智如愚
大智若愚
大月
大有人在
大有作为
大有可为
大有希望
大有文章
大有裨益
大本营
大杀风景
大杂烩
大杂院
大杂院儿
大权
大权在握
大材小用
大样
大桥
大桶
大棒
大楼
大款
大步
大步流星
大步走
大殿
大气
大气压
大气压力
大气压强
大气圈
大气层
大气污染
大气环流
大水
大汉
大汗
大汗淋漓
大江南北
大河
大洋
大洋洲
大洲
大浪
大海捞针
大清早
大游行
大满贯
大灭绝
大灯
大灾
大熊猫
大熔炉
大爆炸
大片
大狱
大猩猩
大理
大理岩
大理石
大略
大病
大白于天下
大白天
大白菜
大白话
大盘子
大相径庭
大破大立
大神
大票
大祸
大米
大粪
大红
大红大紫
大红大绿
大纲
大绝灭
大老婆
大老粗
大老远
大考
大肆
大肆攻击
大股东
大脑死亡
大脚
大腕
大腕儿
大舅子
大范围
大茴香
大草原
大获全胜
大萧条
大葱
大蒜
大蒜末
大行其道
大街
大街小巷
大衣
大袋子
大褂儿
大西洋
大要
大规模
大言
大言不惭
大计
大调
大谈
大谈特谈
大象
大货车
大费周章
大赛
大赦国际
大起大落
大跌
大路
大路货
大踏步
大运河
大进大出
大连
大道理
大部
大都
大都会
大都市
大酒店
大量生产
大钢琴
大锅
大错
大锤
大镰刀
大闹
大队
大陆性
大陆架
大陆漂移
大限临头
大限到来
大院
大陪审团
大难
大雁
大雁塔
大雾
大面额
大韩航空
大项
大题小作
大风雪
大饱口福
大饱眼福
大饼
大马哈鱼
大马路
大驾
大骂
大麦
大黄蜂
大龄
大龄青年

凡响
凡夫
凡夫俗子
凡尘
凡间

飞出
飞升
飞扬跋扈
飞机失事
飞来横祸
飞沫四溅
飞涨
飞溅
飞短流长
飞禽走兽
飞蛾扑火
飞行员
飞行甲板
飞行记录
飞越
飞身
飞转
飞针走线
飞鸽
飞鹰
飞鹰走马

干什么
干净俐落
干吗
干嘛
干嚎
干女儿
干妈
干将
干尸
干巴巴
干干净净
干戈
干掉
干果
干枯
干校
干洗店
干活儿
干流
干涩
干涸
干渴
干煸
干燥剂
干爹
干瘦
干瘪
干着急
干笑
干等
干粉
干系
干练
干脆利落
干草
干菜
干警
干透
干道
干酪

**Comment by yawnoc** [comment]
Thank you. Selected phrases have been added (<https://github.com/stroke-input/stroke-input-data/compare/v1.16.0...v1.17.0>)
