### ISSUE TITLE
The expected sequence to input 拜 doesn’t work

### ISSUE THREAD

**Issue by Greenactivist** [yawnoc/stroke-input-data#4]
the sequencs: ㇒㇐㇐㇑㇐㇐㇐㇐㇑ should yield the character 拜 but it doesn’t.  In fact I couldn’t find any sequence that does.  Apart from that your stroke input method is fantastic.  Thanks for all the work you have put in.

**Comment by yawnoc** [comment]
Thank you for the report!

I counted the 4th stroke of 拜 as a left-slash (㇒), but agree that we should also allow vertical (㇑). This would make it consistent with 掰 and 搿, which already have this leniency for the 4th stroke.

This will be fixed in the next release of stroke-input-android.

**Comment by Greenactivist** [comment]
Thanks for your fast response.  I had thought the fourth stroke should be a vertical because that’s what produces the character 手, which looks like the left hand side of 拜. However in characters such as 看, where the radical appears on top the left-slash seems logical.


-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



16 Jul 2022, 5:45 am by ***@***.***:
