### ISSUE TITLE
Input sequence for U+488E 䢎 contains a lot of redundancy.

### ISSUE THREAD

**Issue by Greenactivist** [yawnoc/stroke-input-data#5]
Currently the input sequence for 䢎 is: 
      (1132|113112)(454|4454|4554).
Unless I have missed something here, I would have thought 
      1132454 
would be sufficient, making it the same as for U+8FDB 进.

**Comment by yawnoc** [comment]
- `(1132|113112)` allows for 开 (modern) and 幵 (olden).
- `(454|4454|4554)` allows for ⻌ (simplified), ⻍ (olden), and ⻎ (modern).

I don't like prescribing certain standards over others.

Arguably it makes no sense to allow `113112` 幵 and `454` ⻌ simultaneously, but excluding such cases would take a lot of effort, and make the data set less readable (and maintainable).

---

进 on the other hand is a strictly simplified character. Therefore only the simplified form of the radical is included.

**Comment by Greenactivist** [comment]
That makes sense.
