### ISSUE TITLE
Is this phrase list of any use to you?

### ISSUE THREAD

**Issue by Greenactivist** [yawnoc/stroke-input-data#8]
I thought this list might be of use to you.  As part of a consistency  check I extracted all the phrases in the dictionary I am creating that start with “一” -- the entries are stored in tree structures with the first character as root.   It occurred to me that you might  find some of them useful to include in phrases-simplified.txt - I’m afraid my dictionary only uses simplified characters as present.

So I stripped out the formatting and deleted all the phrases that occur in your list.  There are still quite a lot of them but the tree under “一” is one of the larger ones..

I don’t suppose you would want to use them all but you might get some idea of extra phrases you could use.  If you find this useful I could supply you with further lists as a check more of the dictionary.  Most will be a lot smaller!

---------------------------------------------

List of phrases using simplified Chinese Characters
Compiled by Bernard Hurley
Released unequivocally to the public domain

一一对应
一丁不识
一丁点
一世
一丘之貉
一丝一毫
一个人
一个样
一串
一举
一举成功
一五一十
一代
一件
一份
一会儿
一位
一体
一体化
一共
一决雌雄
一刀两断
一分一毫
一分为二
一分钱
一分钱一分货
一切事物
一切从简
一切就绪
一则
一刹那间
一刻钟
一动不动
一匙
一千万
一去不回
一去不复返
一反常态
一口
一口咬定
一口气
一句话
一号
一同
一吐为快
一周
一命呜呼
一品
一哄而散
一哄而起
一唱一和
一回事
一团火
一团糟
一块
一堆
一声不吭
一声不响
一夜成名
一夜爆红
一夜致富
一大堆
一大早
一天到晚
一夫一妻
一头
一头栽进
一套
一如既往
一字不差
一字不提
一字不识
一字千金
一定要
一审
一家
一家之主
一家子
一小撮
一尘不染
一层
一展身手
一巴掌
一带
一带而过
一席之地
一席话
一干二净
一年到头
一年四季
一年多
一年生
一年级
一应
一应俱全
一心
一心一德
一心二用
一念之差
一惊一乍
一愁莫展
一意
一成不变
一房一厅
一所
一扇
一手
一手包办
一打
一技之长
一把好手
一折两段
一拍即合
一拥而上
一拥而入
一挥而就
一排
一掷千金
一揽子
一支
一改故辙
一整天
一方
一旁
一族
一无所动
一无所知
一无所获
一无所长
一日千里
一旦
一早
一时
一时冲动
一时半会
一时半刻
一时半刻
一时半晌
一时间
一晃
一月
一月份
一望无际
一本万利
一本正经
一条
一条心
一条龙
一来二去
一杯羹
一板一眼
一根
一根筋
一概
一概而论
一模一样
一次
一次性
一步一步
一气
一气之下
一波一波
一波三折
一派谎言
一流
一清二白
一清如水
一溜烟
一潭死水
一点
一点一滴
一点不
一点也不
一点儿
一点点
一点钟
一片
一物降一物
一生
一病不起
一百万
一盒
一盘散沙
一目十行
一直以来
一直往前
一直走
一眨眼
一眼
一眼望去
一眼看穿
一睹
一瞬
一矢中的
一种
一穷二白
一窍不通
一笑了之
一笑了之
一等
一等奖
一筹莫展
一箩筐
一箭之仇
一箭双雕
一系列
一级
一纸空文
一线
一维
一缕
一股脑
一股脑儿
一脉相承
一脸茫然
一腔
一臂之力
一致性
一般人
一般性
一般来讲
一般来说
一般而言
一般而论
一般见识
一般说来
一落千丈
一行
一衣带水
一表人材
一见倾心
一见高低
一览无遗
一言一行
一言不发
一言为定
一言为重
一言九鼎
一言千金
一言难尽
一语不发
一语中的
一语双关
一诺千金
一贫如洗
一贯
一走了之
一趟
一跃而起
一路上
一路平安
一蹴而就
一蹴而得
一蹶不振
一身两役
一转眼
一辈子
一边
一连
一连串
一遍
一道
一针见血
一钱不值
一错再错
一锤定音
一门心思
一闪而过
一问三不知
一阵子
一霎眼
一霎间
一面
一面之交
一面之词
一项
一饮而尽
一饱眼福
一马平川
一马当先
一鳞半爪
一鸣惊人

**Comment by yawnoc** [comment]
I must admit that the phrase lists are heavily skewed towards what I envisage myself typing; it's a highly vested interest. There's a balance between a comprehensive listing and keeping things lightweight.

The following looked interesting to me: 一旦, 一早, 一時, 一條, 一條龍, 一概, 一概而論, 一模一樣, 一貫, 一連, 一點

Also the following number-based phrases: 一號 etc., 一年 etc., 一月 etc., 一日 etc.

**Comment by yawnoc** [comment]
But yes, this list is useful in that it jogs my memory and reminds me of common phrases that I have omitted.

**Comment by Greenactivist** [comment]
I'm glad you found the list useful.
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



4 Sept 2022, 11:57 am by ***@***.***:
