### ISSUE TITLE
Phrase list 2

### ISSUE THREAD

**Issue by Greenactivist** [yawnoc/stroke-input-data#9]
Here is another list of phrases from my dictionary, not including any you have used. I hope you find some of them useful.

===============================================|

List of phrases using simplified Chinese Characters
Compiled by Bernard Hurley
Released unequivocally to the public domain

乙方
乙肝

八仙桌
八分之一
八卦拳
八卦掌
八卦阵
八国集团
八块腹肌
八天
八字步
八度
八成
八成新
八抬大轿
八拜之交
八方
八月份
八角形
八路军
八边形
八达岭
八进制
八重奏
八面玲珑
八音盒

厂主
厂址
厂子
厂家
厂牌
厂矿
厂规
厂长

刀光血影
刀具
刀刃
刀口
刀叶
刀山火海
刀疤

刁妇
刁滑
刁蛮
刁钻
刁钻古怪

丁克
丁字
丁字尺
丁字路口
丁点
丁点儿
丁香

儿媳妇
儿歌
儿科
儿童医院
儿童节

二人世界
二人转
二代
二元
二分之一
二分点
二十
二十五
二叉树
二号人物
二合一
二哥
二声
二奶
二婚
二婚头
二度
二心
二战
二房
二房东
二手房
二手货
二把刀
二把手
二更
二月份
二次大战
二氧化硅
二流子
二环
二等舱
二级
二老
二者
二者之一
二胎
二话
二话不说
二轮
二进制
二进宫
二道贩子
二重
二重唱
二重奏
二重性

几个月
几乎不
几乎完全
几乎没有
几何学
几内亚湾
几十万
几千
几号
几天来
几年来
几方
几月
几月几号
几比几
几点
几点了
几率
几百

九个
九九归一
九分之一
九十
九头鸟
九月份
九江市
九渊
九牛一毛
九牛二虎之力
九边形
九重霄
九零后
九霄云外

了不得
了不起
了却
了如指掌
了结

力争上游
力作
力保
力图
力大无比
力尽神危
力度
力戒
力所能及
力挽狂澜
力气
力求
力矩
力行
力量均衡

七七八八
七上八下
七八月份
七十
七十年代
七喜
七嘴八舌
七夕
七夕节
七彩
七手八脚
七扭八歪
七拐八弯
七拼八凑
七星瓢虫
七月份
七窍
七窍生烟
七老八十
七角形
七边形
七零八碎
七零八落
七项全能

人世
人世间
人之常情
人事不知
人事处
人事部
人事部门
人人有责
人人皆晓
人人皆知
人体器官
人体工学
人体解剖
人保
人力资源部
人力车夫
人去楼空
人口学
人口数
人口调查
人各有志
人名
人困马乏
人均
人头狮身
人寰
人寿年丰
人寿险
人尽其才
人山人海
人工授精
人工智能
人工流产
人形
人心所向
人心难测
人情世事
人情世故
人才交流会
人才外流
人才流失
人才济济
人文
人文主义
人文景观
人无完人
人机界面
人权斗士
人来疯
人杰
人杰地灵
人格魅力
人模狗样
人死
人民利益
人民大会堂
人民大学
人民政府
人民日报
人民法院
人民警察
人民银行
人浮于事
人渣
人满为患
人烟
人烟稀少
人烟稀疏
人物描写
人物画
人生地不熟
人生朝露
人生观
人种
人称
人穷志短
人类学
人精
人缘
人缘儿
人老珠黄
人肉搜索
人脉
人臣
人行横道
人财两空
人身事故
人迹罕至
人造丝
人造纤维
人道主义
人道救援
人间天堂
人间蒸发
人非圣贤
人面兽心
人高马大

入不敷出
入世
入伙
入会
入住
入党
入关
入口处
入味
入土
入场式
入场费
入境卡
入境随俗
入学率
入学考试
入席
入座
入情入理
入手
入时
入木三分
入盟
入眠
入神
入耳
入药
入行
入迷
入门课程
入院

十一
十一月份
十七
十万
十万火急
十三
十三陵
十之八九
十九
十二
十二分
十二时辰
十二月份
十二边形
十五
十亿
十位
十倍
十克
十八
十六
十几个月
十分之一
十四
十字
十字军
十字形
十字转门
十成
十月份
十有八九
十角形
十进
十进制
十里洋场
十项
十项全能

又一次
又名
又吵又闹
又好
又好气又好笑
又矮又胖
又红又肿
又高又瘦

才华出众
才华横溢
才华盖世
才女
才子佳人
才学
才干
才德
才智
才气过人
才略
才疏学浅
才艺技能
才识过人

叉子
叉形
叉架
叉腰

川流不息

寸草不生

**Comment by yawnoc** [comment]
Thank you.

Selected phrases were added in <<https://github.com/stroke-input/stroke-input-data/commit/c9f0ecc6d7cfb64abd16ae8a8a266a38ca68dd48#diff-fa5757c58f7d90b69fcc570c646783c2fce2ea16aaa9ea6e085e6bda8261a947>>.
